### ISSUE TITLE
Notes missing from CSVProc file generated from VLD file

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1426]

**Comment by AnneV-Learn** [comment]
Issue reported by @geoffj-FUG 

issue:

I have just downloaded RG11_2348.vld as a CSVPro in order to correct an entry reported by a researcher as incorrect. The incorrect information was in the notes. However when I downloaded the file the notes are missing from the whole piece. The notes did download properly until a couple of weeks ago when the suspect deleted flag warning was included in that column. The warning is no longer there so I am wondering whether the notes got removed as well at that change? This is the first vld fil I have dowloaded as csvpro since the change.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG fix has been deployed to Test3 (as per our feedback email communications. Could you please test?

**Comment by geoffj-FUG** [comment]
Anne
I have just downloaded RG10_2500.vld from test 3. The notes are now appearing.
However, the message 'Deleted flag set on VLD; ' is now appearing on the spreadsheet. 
In addition, we still have the problem of the notes downloaded twice, the two downloads concatenated.
Geoff

**Comment by PatReynolds** [comment]
This cannot be pushed to live until the Deleted flag issue and the notes field fixed. @AnneV-Learn can you ask Geoff if you need additional information is needed on what these problems are.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Test3 has now been updated with code that I hope will fix the issue raised in your comment above. Please retest on Test3.

**Comment by geoffj-FUG** [comment]
Anne
This looks OK now. If we can move it to production I will retry it with the file that the problemm was identified in in the first place. Coordinators have been told not to use the vld download at the moment so I will be the only one who knows it can be used. If all is OK I will put it on the coordinators board that it is working again.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this has now been deployed to the production environment.

**Comment by geoffj-FUG** [comment]
Tested in production and all working well.
