### ISSUE TITLE
N/A choice in Gazetteer is now being treated as an advanced search

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1473]
@AnneV-Learn When we added the N/A option to the Gazetteer search radio buttons it has been treated as an advanced search. That means that we can no longer do searches in inverted commas or Boolean searches. Can we recode that so it only cancels any choice in the other 4 buttons.
While we are at it can we change the wording on the Clear County button to Clear Form as that is what it is doing.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Resolved bug that affected ability to do searches in inverted commas or Boolean searches.
Actually Clear County button was not clearing the Search Place Name Text but was resetting the Advanced Search option to N/A as well as clearing the County. I have fixed so that it now just clears the County. 
**Now ready for Testing on Test3.**
Sorry but I am unable to change the Pipeline or add Labels in ZebHub (issue since access re-instated), I have contacted Denise to see if she can resolve.

**Comment by geoffj-FUG** [comment]
Anne
That looks good. It can be deployed.
Geoff

**Comment by DeniseColbert** [comment]
@geoffj-FUG to look again and feed back issues

**Comment by geoffj-FUG** [comment]
@AnneV-Learn We still have a problem here. It is not working properly in production.
When we select a new search from the breadcrumbs we need to reset the radio buttons to N/A.
When the selection is N/A we need to be able to enter a place name in inverted commas to allow a more refined search or a Boolean search.
When we select Clear County we need to reset the form. Maybe we should make this clear form and restore it to a blank.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Sorry but Im still not entirely clear how to proceed here.
I matched the 'preloading of the advanced search options' to the 'preloading of search terms' - see note at top of the form ‘**Previous search name preloaded**.’ functionality but I can remove that functionality for the advanced search options if that is what is required. Please confirm.

I thought the whole purpose of adding the Clear County was to avoid the 'nuisance' of having to scroll to the top of the dropdown to clear the county? Not sure about changing that to a Clear Form. Please confirm.

There is no specific code for the searches using inverted commas (Boolean?) that functionality is just a feature of the Mongodb Text search which I have not modified at all. (When I resolved the bug that affected ability to do searches in inverted commas or Boolean searches in my comment above - it was related to the validation rules for the advanced search and I made no changes to the actual functionality of the regular/inverted commas type searches (ie non-advanced). Can you please give me an example of a search that is not returning the results you expect?

**Comment by DeniseColbert** [comment]
@geoffj-FUG to test strings not rejected

**Comment by DeniseColbert** [comment]
@geoffj-FUG to supply more info on what is needed

**Comment by geoffj-FUG** [comment]
@geoffj-FUG to clarify

**Comment by geoffj-FUG** [comment]
OK lets rethink this.
The default screen has a blank place name to be searched for, the radio buttons set to N/A and a  blank county. 
Boolean searching of a place name should be possible in the default screen with the N/A option selected.
If a place name has two strings with a space the default search is an OR search if the radio button is set at N/A. 
If the two words in the place name are in inverted commas then they are treated as one string with the space being included in the string when the radio button is set to N/A
If the radio button is not N/A only simple searching is possible. Simple searches are for strings without a space character and no Boolean parameters.
The action button should read Clear Screen so that everything is set back to the default.
If the radio button is set to any option other than N/A only simple searches are allowed. Simple searches are a single string of characters with no spaces.
Question - How difficult is it to add the ability to enter a * or ? in the N/A search option?
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Initial question - what do you want to do about ‘Previous search name preloaded’ (which is functionality that pre-dates any changes that I have made)? Are you saying that you want that functionality removed?

**Comment by AnneV-Learn** [comment]
@geoffj-FUG another point to consider. 
As it stands at the moment if you want to search for a whole string eg ‘Leigh on sea’ you can use the Advanced Search ‘Starts with’ or ‘Contains’ option and the full string including the space (nb don’t enclose the string  in inverted commas) is used in the search.

**Comment by geoffj-FUG** [comment]
Anne
As I see it we have a default form with no entries. We need to access this form. So Clear form will achieve this. (See at the end where I challenge the existing logic)
If we are using the breadcrumbs to go back to search place names we get the form as it filled in was during the search that the results are displayed for. The breadcrumbs just take us back. 
That leaves us with the original problem of clearing the county. Maybe we need an extra button that just removes the county and restores the radio buttons to N/A.
I am beginning to question the logic of the original search Gazetteer options. We inherited them. I would prefer it if the options were on the results display.
Does it make it easier if we have 2 options on the search results display?
New Search and
Revise search
New search takes us back to the default search form (blank) and revise search takes us back to the search that produced the results. In that case we just need a button that can remove the county and make it blank. The rest of the form would remain prefilled.
That seems a lot more logical to me. Your thoughts please.
Geoff

**Comment by geoffj-FUG** [comment]
Regarding the advanced searches I was not aware that we can have a space character in them. That seems to be new as it used be refused as a search. I have just tried a contains with a space and it works. I used to wonder why we could not do that but we hhad too much more important work to worry about. So you are right.
I used to enclose the phrase in inverted commas and get Advanced search must contain alphabetic characters only as a response. I obviously did not understand that we could search without the inverted commas. We live and learn!
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have made updates and it is available to test on Test3. There is now a 'Clear Form' button at the top of the Search Criteria form  - I put it there to keep it away from the 'Search Place Names' button, so that it wasn't clicked by mistake but I can easily move it if you would rather it was somewhere else. There are also 'Revise Search' and 'New Search' buttons at the top of the Search Results page. The bug in the 'Clear County' button has been sorted I think.
It is not possible to include a wildcard search (* or ?) in the standard search as it is what is called a Text Search which special sort of search that automatically includes the following functionality: 
Stemming (the process of reducing words to their stem e.g. words like Ford, Fords have a common base Ford;
Stop words (the process of filtering out irrelevant words e.g. a , at, on etc.);
Scoring (i.e. ranking to measure which of the search results is most relevant.

**Comment by geoffj-FUG** [comment]
Anne
We did have the ability to use enter after the place and it would start the search. Can we restore that please?
Otherwise it is just the buttons at the top of teh default search page. Can we put Clear form in the centre as it is and then Create New FreeCEN Place on the right hand end of the same line.? That will present a neat page for most users. Clear Form is in the right position on the transcribers view of the form.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG, I have made some changes which I hope resolve your comments above. It is ready to re-test on Test3.

**Comment by geoffj-FUG** [comment]
Anne

Looks good.

I think we are there this time.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have made the changes related to the User feedback and they are ready for testing in TEST3

**Comment by geoffj-FUG** [comment]
Anne
Now that works well and it is neat and tidy. Lets go with it.
Geoff

**Comment by DeniseColbert** [comment]
Deployed: closing
