### ISSUE TITLE
Search record info not being sent with Data Problem report (142679887 Data Problem (Denise Colbert))

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#709]
Issue reported by **Denise Colbert** at 2019-07-10 09:18:07 UTC
Time: 2019-07-10T09:17:25+00:00
Session ID: 8533b375b44d7d8795c94796ec49d044
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freecen.org.uk/contacts/59028104e9379091b135d285/report_error?locale=en](https://www.freecen.org.uk/contacts/59028104e9379091b135d285/report_error?locale=en)
Reported Issue:
Testing... Hi Brenda :)    

![Screenshot](https://www.freecen.org.uk)
************************************************
1. I didn't upload an image so why is there a screenshot link (albeit broken)?
2. Problem page URL shouldn't be 'unknown'. In this instance it was https://www.freecen.org.uk/search_records/59028104e9379091b135d285/joseph-smith-1891-bedfordshire-ampthill-1890-?locale=en

Could this be caused by move to multimodal?

E 3, U8, S7, C8: P26

**Comment by richpomfret** [comment]
@Vino-S could you take a look at this?

**Comment by PatReynolds** [comment]
Testing - with attachment.to Data Question and Website Problem as not sure which was broken!

@FreecenBren did you get both, OK?

**Comment by Captainkirkdawson** [comment]
Neither. It is the reporting of a Data Problem from the search results detail page

**Comment by richpomfret** [comment]
@Vino-S Looks like this isn't fixed yet on test3.

**Comment by richpomfret** [comment]
Ready to be tested again.

**Comment by Vino-S** [comment]
1. Added code to send problem Search Record information which is sent as mail to Coordinator 
2. Also made changes in the code to display link to problem Search Recod Detail page in github issue.

@Captainkirkdawson Do we need to test the code in FreeREG also ?

**Comment by Captainkirkdawson** [comment]
Will look at it Saturday. It was already working correctly on REG. I believe CEN uses different code in places but a test for unintended consequences is needed.

**Comment by Captainkirkdawson** [comment]
@Vino-S have now had a chance to look at the implementation and am unsure that it really addresses the story as the issue is still there.  The following is a data report done today on test3 which is running issue_709.
![cendp.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/fa649ec6-2a71-4ceb-878e-5cdc4f313504)
There is no link to the search record that has the problem. Neither if there an entry for the county.  
Nor is there a county link in the index of comments
![cendp1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/512199aa-39a0-4a0c-848c-7e676a135af4)

See reg data problem display for what the information that the story likely should be delivering

![regdp.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/94d22a4b-f6ff-482f-aed2-984d5bc92b91)

The communication to the coordinator does not have a link to the record either but it does extract the data and place it in the email itself. However that extraction may or may not be relevant to what the researcher has seen or on which they are commenting.

**Comment by Captainkirkdawson** [comment]
Have just received the info the coordinator receives. There is insufficient into for them to respond. They need a link to the search record the researcher saw

![cendp2.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9185de35-25ea-4cb9-9b34-8f9466071f69)

**Comment by richpomfret** [comment]
@Vino-S can you comment or update?

**Comment by Vino-S** [comment]
ready for testing on test3

**Comment by Vino-S** [comment]
fixed. Ready to be tested on test2

**Comment by richpomfret** [comment]
@DeniseColbert please test if you get a chance.

**Comment by DeniseColbert** [comment]
Tested in test2. Record/session data seems to be included:
![image](https://user-images.githubusercontent.com/19173257/66472830-f5fc1880-ea85-11e9-8589-90681ecadc2b.png)

However, the county is still missing from the list:
![image](https://user-images.githubusercontent.com/19173257/66472866-0b714280-ea86-11e9-86f4-88b6311991eb.png)

**Comment by Vino-S** [comment]
@DeniseColbert , apologies test2 was running on another branch. I have switched the branch to reflect code changes for this issue. Can you test it again, please.

**Comment by DeniseColbert** [comment]
Tested and now seems fine :)

**Comment by Vino-S** [comment]
Thanks @DeniseColbert

**Comment by richpomfret** [comment]
Closing.
